### DISCUSSION TITLE
Issues setting this up with Nginx Proxy Manager instead of Caddy

### DISCUSSION THREAD

**Discussion by loof2736** [PhlexPlexico/G5API#298] [Help] [answered]
Since I already have Nginx Proxy Manager running separately, I removed the caddy sections from the docker compose and opened port 80 and 3301 on the API and front end:

```
services:
  redis:
    image: redis:6
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: redis
    networks:
      - get5
    restart: unless-stopped
  get5db:
    image: yobasystems/alpine-mariadb
    container_name: get5db
    restart: unless-stopped
    networks:
      - get5
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    networks:
      - get5
    volumes:
      - /home/docker/Get5API/public:/Get5API/public
    environment:
      - NODE_ENV=production
      - PORT=3301
      - DBKEY=${DB_KEY}
      - STEAMAPIKEY=${STEAM_API_KEY}
      - HOSTNAME=G5API
      - SHAREDSECRET=${SHARED_SECRET}
      - CLIENTHOME=https://get5.domain.com
      - APIURL=https://get5.domain.com/api
      - SQLUSER=get5
      - SQLPASSWORD=${MYSQL_PASSWORD}
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=
      - SUPERADMINS=<steamid>
      - REDISURL=redis://:${REDIS_PASSWORD}@redis:6379
      - REDISTTL=86400
      - USEREDIS=true
      - UPLOADDEMOS=true
      - LOCALLOGINS=false
    restart: unless-stopped
    ports:
      - 3301:3301
  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on:
      - g5api
    container_name: G5V-Front-End
    ports:
      - 80:80
    networks:
      - get5
    restart: unless-stopped
networks:
  get5: null

```

Looking at the docker logs, there are no errors or any indication anything is failing. 

In Nginx Proxy Manager, I created a new proxy host set to forward the get5 subdomain to the local IP on port 80 (192.168.1.105:80). Then I added a custom location for the API that points the location "/api/*" to 192.168.1.105:3301

I'm able to get to the homepage, but as soon as I click "Sign in through STEAM" it redirects me to "https://get5.domain.com/api/auth/steam" which is just a blank Get5Vue page. I still see the header and footer, but no content in the middle.

If I manually go to 192.168.1.105:3301 in a browser, I do get to the steam sign in page. When I click "Sign in" though, I go back to the same empty Get5Vue page, but this time the URL includes a /return? after /steam and a bunch of auth stuff

Not sure what the issue is, I see no errors in the browser console or the docker logs for any of the containers

**Comment by PhlexPlexico** [comment]
Hmm. This may be a configuration issue. I know my public panel is behind a separate Caddy reverse proxy. I think I still kept the proxy in the docker compose file, and just dropped the reverse proxy on a different port and used my reverse proxy that's public facing to point to it. For example:

```
caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy-reverse-proxy
    #restart: unless-stopped
    networks:
      - shared
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:80"
    environment:
      - CADDY_INGRESS_NETWORKS=get5

  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    networks:
      - shared
    labels:
      caddy: get5.phlexplexi.co
      caddy.handle_path: /api/*
      caddy.handle_path.0_reverse_proxy: "{{upstreams 3301}}"
    volumes:
      - ./public:/Get5API/public
    environment:
      - NODE_ENV=production
      - PORT=3301
      - DBKEY=aaaa
      - STEAMAPIKEY=aaaa
      - HOSTNAME=https://get5.phlexplexi.co
      - SHAREDSECRET=a secure secret for jwt sigining.
      - CLIENTHOME=https://get5.phlexplexi.co
      - APIURL=https://get5.phlexplexi.co/api
      - SQLUSER=get5
      - SQLPASSWORD=aaa
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=
      - SUPERADMINS=76561198025644194
      - REDISURL=redis://:aaaa@redis:6379                                         
```
And my reverse proxy that's public facing looks like this

```
get5.phlexplexi.co {
  reverse_proxy G5V-Front-End
  request_body {
   max_size 256MB
  }
  redir /api /api/
  route /api/* {
  uri strip_prefix /api
  reverse_proxy http://G5API:3301
  }
}
```

I think this could be consolidated into one caddy tag, but I've found that this works with minimal modifying of the compose file.

It's odd, and a bit hacky, but I do remember having some issues when removing the reverse proxy from the docker compose, and this seemed to fix it.

Thanks!
