### ISSUE TITLE
[BUG]Problems with the start-up docker-compose as a local set up

### ISSUE THREAD

**Issue by MJPetermann** [PhlexPlexico/G5API#216]
Hi,
I'm currently trying to set up a local CS:GO tournament and would therefore like to run the API and web interface locally. I already tried setting both up using the docker-compose.yml the last three days, but ran into issues in the process. 

**The Error**
Every time docker compose is run, it displays this error message:

G5API     | yarn run v1.22.19
G5API     | $ MYSQL_FLAGS="-CONNECT_WITH_DB" db-migrate --env production --config config/production.json db:create get5
G5API     | [ERROR] SyntaxError: Unexpected token } in JSON at position 377
G5API     |     at JSON.parse (<anonymous>)
G5API     |     at exports.parse (/Get5API/node_modules/rc/lib/utils.js:15:17)
G5API     |     at addConfigFile (/Get5API/node_modules/rc/index.js:30:20)
G5API     |     at module.exports (/Get5API/node_modules/rc/index.js:46:20)
G5API     |     at module.exports (/Get5API/node_modules/db-migrate/lib/commands/set-default-argv.js:122:47)
G5API     |     at new dbmigrate (/Get5API/node_modules/db-migrate/api.js:75:10)
G5API     |     at Object.module.exports.getInstance (/Get5API/node_modules/db-migrate/index.js:85:10)
G5API     |     at /Get5API/node_modules/db-migrate/bin/db-migrate:32:25
G5API     |     at /Get5API/node_modules/resolve/lib/async.js:142:25
G5API     |     at maybeRealpath (/Get5API/node_modules/resolve/lib/async.js:50:9)
G5API     | error Command failed with exit code 1.
G5API     | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**What i've tried**
Due to a similar error in issue #148 I tried using the solutions you gave there, but wasn't successful with that.
Here's a list of what I've tried:

- used local IPs e.g. "192.168.178.108"
- used the hostname, which my router gives to every device in the network e.g. "mj-server" due to the docs stating it not to work with a ip address
- tried the configuration with duckdns (with port forwarding port 80 and 433)
- tried every combination with "http://", "https://" and nothing in front
- tested the config on my local server (using Ubuntu 22.04 LTS), my laptop (using Windows 11) and my Raspberry Pi 4 (using 64bit Raspian OS lite)

Every time I got the same error as shown above, with the only change seen in the unexpected token. It changed position every time I changed values in the docker-compose.yml in front of the SQLUSER in the g5api section. The full docker-compose.yml is attached.

Now, I'm not sure if I can use the G5API in conjunction with the Web interface on a local network without exposing them publicly. So is it possible?
I'm sorry if it's a simple issue, I've overlooked or didn't get something clearly written in the docs. I read everything in the docker-compose and configuration section twice or more and still am unsure on if I misunderstood something. Also, I'm neither someone who gets to work with Docker and networking often, nor is English my first language. 

the docker-compose.yml
```
version: "3.7"

services:
  redis:
    image: redis:6
    command: redis-server --requirepass <passRedis>
    container_name: redis
    networks:
      - get5
    restart: always

  get5db:
    image: yobasystems/alpine-mariadb
    container_name: get5db
    restart: always
    networks:
      - get5
    environment:
      - MYSQL_ROOT_PASSWORD=<passMaria>
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=<passG5SQL>

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy-reverse-proxy
    restart: unless-stopped
    networks:
      - get5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=get5

  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    networks:
      - get5
    labels:
      caddy: <mydomain>.duckdns.org
      caddy.handle_path: /api/*
      caddy.handle_path.0_reverse_proxy: "{{upstreams 3301}}"
    volumes:
      - ./public:/Get5API/public
    environment:
      - NODE_ENV=production
      - PORT=3301
      - DBKEY=<dbkey>
      - STEAMAPIKEY=<steamapikey>
      - HOSTNAME=https://<mydomain>.duckdns.org
      - SHAREDSECRET=<supersecretsecret>
      - CLIENTHOME=https://<mydomain>.duckdns.org
      - APIURL=https://<mydomain>.duckdns.org/api
      - SQLUSER=get5
      - SQLPASSWORD=<passG5SQL>
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=76561198355583930
      - SUPERADMINS=76561198355583930
      - REDISURL=redis://:<passRedis>@redis:6379
      - REDISTTL=86400
      - USEREDIS=true
      - UPLOADDEMOS=false
      - LOCALOGINS=true
    restart: always

  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on:
      - g5api
    container_name: G5V-Front-End
    networks:
      - get5
    restart: always
    labels:
      caddy: <mydomain>.duckdns.org
      caddy.reverse_proxy: "{{upstreams}}"

networks:
  get5:
    external: true
```

**Comment by MJPetermann** [comment]
the docker-compose.yml
```
version: "3.7"

services:
  redis:
    image: redis:6
    command: redis-server --requirepass <passRedis>
    container_name: redis
    networks:
      - get5
    restart: always

  get5db:
    image: yobasystems/alpine-mariadb
    container_name: get5db
    restart: always
    networks:
      - get5
    environment:
      - MYSQL_ROOT_PASSWORD=<passMaria>
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=<passG5SQL>

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy-reverse-proxy
    restart: unless-stopped
    networks:
      - get5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=get5

  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    networks:
      - get5
    labels:
      caddy: <mydomain>.duckdns.org
      caddy.handle_path: /api/*
      caddy.handle_path.0_reverse_proxy: "{{upstreams 3301}}"
    volumes:
      - ./public:/Get5API/public
    environment:
      - NODE_ENV=production
      - PORT=3301
      - DBKEY=<dbkey>
      - STEAMAPIKEY=<steamapikey>
      - HOSTNAME=https://<mydomain>.duckdns.org
      - SHAREDSECRET=<supersecretsecret>
      - CLIENTHOME=https://<mydomain>.duckdns.org
      - APIURL=https://<mydomain>.duckdns.org/api
      - SQLUSER=get5
      - SQLPASSWORD=<passG5SQL>
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=76561198355583930
      - SUPERADMINS=76561198355583930
      - REDISURL=redis://:<passRedis>@redis:6379
      - REDISTTL=86400
      - USEREDIS=true
      - UPLOADDEMOS=false
      - LOCALOGINS=true
    restart: always

  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on:
      - g5api
    container_name: G5V-Front-End
    networks:
      - get5
    restart: always
    labels:
      caddy: <mydomain>.duckdns.org
      caddy.reverse_proxy: "{{upstreams}}"

networks:
  get5:
    external: true

```
