### ISSUE TITLE
[BUG] error api new Docker compose version

### ISSUE THREAD

**Issue by Iwhite67** [PhlexPlexico/G5API#228]
Hello

i just put the new version on new VM
i take docker-compose.yml and setup all

i have this error
Second part are not link to first because if i put useredis false, i have only second side
```
5API     | /root/.pm2/logs/G5API-out-0.log last 15 lines:
G5API     | 0|G5API    | Redis error:  Error: connect ECONNREFUSED 172.19.0.3:6379
G5API     | 0|G5API    |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
G5API     | 0|G5API    |   errno: -111,
G5API     | 0|G5API    |   code: 'ECONNREFUSED',
G5API     | 0|G5API    |   syscall: 'connect',
G5API     | 0|G5API    |   address: '172.19.0.3',
G5API     | 0|G5API    |   port: 6379
G5API     | 0|G5API    | }
G5API     | 0|G5API    | Redis error:  Error: getaddrinfo ENOTFOUND redis
G5API     | 0|G5API    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
G5API     | 0|G5API    |   errno: -3008,
G5API     | 0|G5API    |   code: 'ENOTFOUND',
G5API     | 0|G5API    |   syscall: 'getaddrinfo',
G5API     | 0|G5API    |   hostname: 'redis'
G5API     | 0|G5API    | }
G5API     |



G5API     | 0|G5API  | GET /isLoggedIn 500 0.635 ms - 47
G5API     | 0|G5API  | GET /isLoggedIn 500 0.612 ms - 47
G5API     | 0|G5API  | GET /leaderboard 500 0.577 ms - 47
G5API     | 0|G5API  | GET /leaderboard/players 500 0.616 ms - 47
G5API     | 0|G5API  | GET /matches/limit/3 500 0.574 ms - 47
G5API     | 0|G5API  | GET /isLoggedIn 500 0.544 ms - 47

```

```
version: "3.7"

services:
  redis:
    image: redis:6
    command: redis-server --requirepass PASSWORD
    container_name: redis
    networks:
      - get5
    restart: always

  get5db:
    image: yobasystems/alpine-mariadb
    container_name: get5db
    restart: always
    networks:
      - get5
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=PASSWORD
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy-reverse-proxy
    restart: unless-stopped
    networks:
      - get5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=get5

  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    networks:
      - get5
    labels:
      caddy: https://match.cs.domaine.fr
      caddy.handle_path: /api/*
      caddy.handle_path.0_reverse_proxy: "{{upstreams 3301}}"
    volumes:
      - ./public:/Get5API/public
    environment:
      - NODE_ENV=production
      - PORT=3301
      - DBKEY=DBKEY
      - STEAMAPIKEY=STEAMKEY
      - HOSTNAME=https://match.cs.domaine.fr
      - SHAREDSECRET=
      - CLIENTHOME=https://match.cs.domaine.fr
      - APIURL=https://match.cs.domaine.fr/api
      - SQLUSER=get5
      - SQLPASSWORD=PASSWORD
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=
      - SUPERADMINS=76561198033164185
      - REDISURL=redis://:PASSWORD@redis:6379
      - REDISTTL=86400
      - USEREDIS=true
      - UPLOADDEMOS=true
      - LOCALLOGINS=false
    restart: always

  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on:
      - g5api
    container_name: G5V-Front-End
    networks:
      - get5
    restart: always
    labels:
      caddy: https://match.cs.domaine.fr
      caddy.reverse_proxy: "{{upstreams}}"

networks:
  get5:
    external: true

```
