### ISSUE TITLE
[BUG] Adding workshop map to season causes 500 on season load

### ISSUE THREAD

**Issue by JesusWithPants** [PhlexPlexico/G5API#237]
**Describe the bug**
Adding workshop map to season causes HTTP 500 on season load.

```
0|G5API  | SyntaxError: Unexpected number in JSON at position 123

0|G5API  |     at JSON.parse (<anonymous>)

0|G5API  |     at file:///Get5API/routes/seasons.js:100:38

0|G5API  |     at runMicrotasks (<anonymous>)

0|G5API  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

0|G5API  | GET /seasons 500 3.068 ms - 68
```
![image](https://user-images.githubusercontent.com/26171332/206859713-6fa6319f-3569-47f2-a2cb-345423b108d2.png)

**To Reproduce**
1. Create a season with including a workshop map (in this case `workshop\1542127528\de_cbble`)
2. On save - no seasons are loaded anymore.

Repeatable on any browser (as this seems to be a backend error)

**CSGO Server info**
Dathost CSGO server instance

**Host info**
Running on a VPS as docker instance, spawned by docker-composer file:
```
version: "3.7"

networks:
  get5:
    external: true

services:
  redis:
    image: redis:6
    command: redis-server --requirepass ${redispassword}
    container_name: get5redis
    networks:
      - get5
    restart: always
    
  get5db:
    image: mariadb
    container_name: get5db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${sqlrootpassword}
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=${sqlpassword}
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
#    ports:
#      - "3306:3306"
    expose:
      - 3306
    networks:
      - get5

  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    volumes: 
      - redisVol:/Get5API/public
#    expose:
#      - 3301
    environment:
      - NODE_ENV=production
      - PORT=3301
      - HOSTNAME=${hostname}
      - DBKEY=${dbkey}
      - STEAMAPIKEY=${steamkey}
      - SHAREDSECRET=${sharedsecret}
      - CLIENTHOME=${home}
      - APIURL=${apiurl}
      - SQLUSER=get5
      - SQLPASSWORD=${sqlpassword}
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=${admins}
      - SUPERADMINS=${superadmins}
      - REDISURL=redis://:${redispassword}@redis:6379
      - REDISTTL=86400
      - USEREDIS=true
      - UPLOADDEMOS=true
      - LOCALLOGINS=false
    restart: always
    networks:
      - get5
    labels:      
      - "traefik.enable=true"
      - "traefik.http.routers.get5api.rule=Host(`get5.domain.tld`) && PathPrefix(`/api`)"
      - "traefik.http.routers.get5api.entrypoints=websecure"
      - "traefik.http.routers.get5api.tls=true"
      - "traefik.http.routers.get5api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.get5api.middlewares=get5api_path@docker"
#      - "traefik.http.routers.get5api.middlewares=get5api_path@docker,get5api_head@docker"
      - "traefik.http.middlewares.get5api_path.replacepathregex.regex=^/api/(.*)$$"
      - "traefik.http.middlewares.get5api_path.replacepathregex.replacement=/$$1"
#      - "traefik.http.middlewares.get5api_head.headers.hostsProxyHeaders=true"

  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on: 
      - g5api
    container_name: G5V-Front-End
    restart: always
    networks:
      - get5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.get5.rule=Host(`get5.domain.tld`)"
      - "traefik.http.routers.get5.entrypoints=websecure"
      - "traefik.http.routers.get5.tls=true"
      - "traefik.http.routers.get5.tls.certresolver=letsencrypt"

volumes:
  redisVol:
    external: false
```
